import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/constants/app_constants.dart';
import '../../domain/models/station.dart';
import '../../domain/models/queue_update.dart';
import 'repository_providers.dart';

/// Stream provider watching all stations.
final stationsProvider = StreamProvider<List<Station>>((ref) {
  final stationRepo = ref.watch(stationRepositoryProvider);
  return stationRepo.watchStations();
});

/// Stream provider watching stations filtered by city ID.
final stationsByCityProvider =
    StreamProvider.family<List<Station>, String>((ref, cityId) {
  final stationRepo = ref.watch(stationRepositoryProvider);
  return stationRepo.watchStationsByCity(cityId);
});

/// Future provider for getting a single station by ID.
final stationProvider =
    FutureProvider.family<Station?, String>((ref, id) async {
  final stationRepo = ref.watch(stationRepositoryProvider);
  return stationRepo.getStation(id);
});

/// Stream provider watching queue updates for a specific station.
final stationUpdatesProvider =
    StreamProvider.family<List<QueueUpdate>, String>((ref, stationId) {
  final queueRepo = ref.watch(queueUpdateRepositoryProvider);
  return queueRepo.watchUpdatesForStation(stationId);
});

/// State for station actions (reporting/confirming).
enum StationActionStatus { idle, loading, success, error }

class StationActionState {
  const StationActionState({
    this.status = StationActionStatus.idle,
    this.errorMessage,
  });

  final StationActionStatus status;
  final String? errorMessage;
}

/// StateNotifier managing station report and confirm actions.
class StationActionsNotifier extends StateNotifier<StationActionState> {
  StationActionsNotifier(this._ref) : super(const StationActionState());

  final Ref _ref;

  /// Report a station's queue status.
  Future<void> reportStatus({
    required String stationId,
    required QueueStatus status,
    required bool hasFuel,
    required FuelType fuelType,
    required String userPhone,
    required double latitude,
    required double longitude,
  }) async {
    state = const StationActionState(status: StationActionStatus.loading);

    try {
      final stationRepo = _ref.read(stationRepositoryProvider);
      final queueRepo = _ref.read(queueUpdateRepositoryProvider);

      // Update station status
      await stationRepo.updateStationStatus(stationId, status, hasFuel);

      // Submit queue update record
      final update = QueueUpdate(
        id: '', // Will be auto-generated by Firestore
        stationId: stationId,
        queueStatus: status,
        hasFuel: hasFuel,
        fuelType: fuelType,
        timestamp: DateTime.now(),
        userPhone: userPhone,
        latitude: latitude,
        longitude: longitude,
      );
      await queueRepo.submitUpdate(update);

      state = const StationActionState(status: StationActionStatus.success);
    } catch (e) {
      state = StationActionState(
        status: StationActionStatus.error,
        errorMessage: e.toString(),
      );
    }
  }

  /// Confirm the current status of a station.
  Future<void> confirmStatus({
    required String stationId,
    required String userPhone,
  }) async {
    state = const StationActionState(status: StationActionStatus.loading);

    try {
      final stationRepo = _ref.read(stationRepositoryProvider);
      await stationRepo.confirmStatus(stationId, userPhone);
      state = const StationActionState(status: StationActionStatus.success);
    } catch (e) {
      state = StationActionState(
        status: StationActionStatus.error,
        errorMessage: e.toString(),
      );
    }
  }

  /// Reset to idle state.
  void reset() {
    state = const StationActionState();
  }
}

/// Provider for station actions (report/confirm).
final stationActionsProvider =
    StateNotifierProvider<StationActionsNotifier, StationActionState>(
  (ref) => StationActionsNotifier(ref),
);
