// GENERATED FILE - DO NOT EDIT MANUALLY
// Run: flutterfire configure --project=queue-6a58d
// This file will be regenerated by FlutterFire CLI

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Run `flutterfire configure --project=queue-6a58d` to generate this file
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform - '
      'run `flutterfire configure --project=queue-6a58d` to generate firebase_options.dart',
    );
  }
}
